FROM node:16-alpine as BUILDER

RUN npm install -g @angular/cli

ADD ./package.json /app/package.json

WORKDIR /app/

RUN npm install 

ADD . /app/

RUN ng build 

FROM nginx:alpine

COPY --from=BUILDER /app/dist/covid-app/ /usr/share/nginx/html